### ISSUE TITLE
Usage Tutorial

### ISSUE THREAD

**Issue by arminolat** [bditt/Strawpoll.me-Bot#3]
Hi! I found this nice piece of software while searching for a working Strawpoll bot. 

I was hoping you could assist me.

First of all, does this still work?
Second, how should I run it on Linux (is it even supported on Linux)?

Thanks!

**Comment by Lucas559-noob** [comment]
it still works, idk if there is the things of newtonsoft for Linux

**Comment by bditt** [comment]
Yes, this still works.
As @Lucas559-noob said, this doesn't work on Linux, but you can easily remake this to work on Linux.
Sorry for late response, didn't notice it.

**Comment by rgowdame** [comment]
does it still work??

**Comment by bditt** [comment]
> does it still work??

Hello, this no longer works due to [https://strawpoll.me]( https://strawpoll.me) being taken down.

The code itself would still work if it was up though.

Do you need this for another strawpoll site?

If so, the fundamentals should relatively be the same.
