### ISSUE TITLE
strawpoll

### ISSUE THREAD

**Issue by Matertime** [bditt/Strawpoll.me-Bot#4]
Hello
My brother
I need a link and explanation for strawpoll

**Comment by Lucas559-noob** [comment]
to get a strawpool id
on link there is something like `strawpoll.me/` copy the numbers, they are the id
then right click on the vote option and click on inspect, there will be something written value = "numbers", copy the numbers
and then how much votes and how much bots will vote(more bots=more of the pc it will use)

get proxy in proxyscrape and download html proxy, open, copy and paste on Proxies

**Comment by bditt** [comment]
Instructions are in the readme.
